!!python/object/apply:collections.OrderedDict
- - [batch_size, 100]
  - [buffer_size, 1000000]
  - [gamma, 0.99]
  - [gradient_steps, 1000]
  - [learning_rate, 0.001]
  - [learning_starts, 10000]
  - [n_timesteps, 1000000.0]
  - [noise_std, 0.1]
  - [noise_type, normal]
  - [policy, MlpPolicy]
  - [policy_kwargs, 'dict(layers=[400, 300])']
  - [train_freq, 1000]
