!!python/object/apply:collections.OrderedDict
- - [cliprange, 0.2]
  - [cliprange_vf, -1]
  - [ent_coef, 0.0]
  - [env_wrapper, utils.wrappers.TimeFeatureWrapper]
  - [gamma, 0.99]
  - [lam, 0.95]
  - [learning_rate, lin_2.5e-4]
  - [n_envs, 4]
  - [n_steps, 1024]
  - [n_timesteps, 2000000.0]
  - [nminibatches, 32]
  - [noptepochs, 10]
  - [normalize, true]
  - [policy, MlpPolicy]
