!!python/object/apply:collections.OrderedDict
- - [ent_coef, 0.0]
  - [env_wrapper, utils.wrappers.TimeFeatureWrapper]
  - [gamma, 0.98]
  - [learning_rate, 0.0217]
  - [lr_schedule, constant]
  - [max_grad_norm, 0.5]
  - [n_envs, 1]
  - [n_steps, 128]
  - [n_timesteps, 2000000.0]
  - [normalize, true]
  - [nprocs, 4]
  - [policy, MlpPolicy]
  - [vf_coef, 0.946]
