!!python/object/apply:collections.OrderedDict
- - [ent_coef, 0.0]
  - [gamma, 0.99]
  - [learning_rate, 0.06]
  - [lr_schedule, constant]
  - [n_envs, 8]
  - [n_steps, 16]
  - [n_timesteps, 5000000.0]
  - [normalize, true]
  - [policy, MlpPolicy]
