!!python/object/apply:collections.OrderedDict
- - [batch_size, 256]
  - [learning_starts, 1000]
  - [n_timesteps, 300000.0]
  - [noise_std, 0.1]
  - [noise_type, ornstein-uhlenbeck]
  - [policy, MlpPolicy]
