!!python/object/apply:collections.OrderedDict
- - [cliprange, 0.2]
  - [ent_coef, 0.0]
  - [gamma, 0.99]
  - [lam, 0.95]
  - [learning_rate, 0.00025]
  - [n_envs, 8]
  - [n_steps, 2048]
  - [n_timesteps, 100000.0]
  - [nminibatches, 32]
  - [noptepochs, 10]
  - [normalize, true]
  - [policy, MlpPolicy]
